spring:
  application:
    name: tos
  datasource:
    url: jdbc:postgresql://localhost:5432/tos_fatec
    username: postgres
    password: 3024
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet: 
    context-path: /api  
  port: 8080  

springdoc:
  api-docs:
    path: /api-docs 
  swagger-ui:
    enabled: true  
    path: /swagger-ui.html 